CATEGORIES = {
    1: ("Project structure", ["server.py", "requirements.txt"]),
    2: ("Telegram integration", ["bot.py"]),
    3: ("Registration", []),
    4: ("Authentication", []),
    5: ("User rights", []),
    6: ("Owner rights", []),
    7: ("Database", []),
    8: ("Migrations", []),
    9: ("Mini App", ["web/index.html"]),
    10: ("Navigation", ["web/app.js"]),
    11: ("Profile", []),
    12: ("History", []),
    13: ("Statistics", []),
    14: ("Admin panel", []),
    15: ("User management", []),
    16: ("Access system", []),
    17: ("Asset selection", []),
    18: ("Asset search", []),
    19: ("Asset categories", []),
    20: ("Favorites", []),
    21: ("Timeframe", []),
    22: ("Result UI", []),
    23: ("Signal flow", []),
    24: ("Technical indicators", []),
    25: ("Advanced analysis", []),
    26: ("AI analysis", ["ai_analyzer.py"]),
    27: ("Photo AI", ["photo_ai.py"]),
    28: ("AI Support", []),
    29: ("Market data", []),
    30: ("Short timeframe feed", ["short_tf_feed.py"]),
    31: ("API", ["server.py"]),
    32: ("Frontend JS", ["web/app.js"]),
    33: ("CSS/UI", ["web/styles.css"]),
    34: ("Gunicorn", ["gunicorn.conf.py"]),
    35: ("Startup configuration", ["sitecustomize.py"]),
    36: ("Network modules", []),
    37: ("Diagnostics", []),
    38: ("Dependencies", ["requirements.txt"]),
    39: ("GitHub Actions", [".github/workflows/main.yml"]),
    40: ("Render/config", ["render.yaml"]),
    41: ("Integrity/error control", []),
}
