# 41 read-only QA categories. Each category points to repository evidence.
CATEGORIES = {
    1: ("Структура проекта", ["server.py", "requirements.txt"]),
    2: ("Telegram Bot", ["bot.py"]),
    3: ("Регистрация", ["server.py"]),
    4: ("Авторизация", ["server.py"]),
    5: ("Права пользователя", ["server.py"]),
    6: ("Права владельца", ["server.py"]),
    7: ("База данных", ["server.py"]),
    8: ("Миграции", ["server.py"]),
    9: ("Mini App", ["web/index.html"]),
    10: ("Навигация", ["web/app.js"]),
    11: ("Профиль", ["server.py"]),
    12: ("История", ["server.py"]),
    13: ("Статистика", ["server.py"]),
    14: ("Admin Panel", ["server.py"]),
    15: ("Управление пользователями", ["server.py"]),
    16: ("Система доступа", ["server.py"]),
    17: ("Выбор актива", ["web/app.js"]),
    18: ("Поиск актива", ["web/app.js"]),
    19: ("Категории активов", ["web/app.js"]),
    20: ("Избранное", ["web/app.js"]),
    21: ("Таймфрейм", ["web/app.js"]),
    22: ("Интерфейс результата", ["web/app.js", "web/styles.css"]),
    23: ("Поток сигнала", ["server.py"]),
    24: ("Технические индикаторы", ["advanced_signals.py"]),
    25: ("Расширенный анализ", ["advanced_signals.py"]),
    26: ("AI Analysis", ["ai_analyzer.py"]),
    27: ("Photo AI", ["photo_ai.py"]),
    28: ("AI Support", ["server.py"]),
    29: ("Market Data", ["server.py"]),
    30: ("Short TF Feed", ["short_tf_feed.py"]),
    31: ("API", ["server.py"]),
    32: ("Frontend JS", ["web/app.js"]),
    33: ("CSS / UI", ["web/styles.css"]),
    34: ("Gunicorn", ["gunicorn.conf.py"]),
    35: ("Startup", ["sitecustomize.py"]),
    36: ("Network Modules", ["server.py"]),
    37: ("Diagnostics", ["server.py"]),
    38: ("Dependencies", ["requirements.txt"]),
    39: ("GitHub Actions", [".github/workflows/main.yml"]),
    40: ("Render / Config", ["render.yaml"]),
    41: ("Integrity / Error Control", ["server.py"]),
}
