function goHome(){home()}\nconst p=new URLSearchParams(location.search),session=p.get("session"),tg=window.Telegram?.WebApp;
if(tg){tg.ready();tg.expand()}
const el=document.getElementById("screen");let data=null,status=null,timer=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function get(u){try{let r=await fetch(u,{cache:"no-store"});return await r.json()}catch(e){return {ok:false,error:e.message}}}
async function sessionLoad(){let r=await get("/api/session?session="+encodeURIComponent(session||""));if(r.ok){data=r}}
function badge(s){return "<span class='badge "+(s==="PASS"?"pass":s==="WARNING"?"warning":s==="FAIL"?"failure":"notbadge")+"'>"+esc(s)+"</span>"}
function nav(n){document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x.dataset.screen===n));({home,results,errors,infra,history}[n]||home)()}
function quick(){return "<div class='quick'><button onclick='nav("results")'><span class='ico'>▥</span><small>Результаты</small></button><button onclick='nav("errors")'><span class='ico'>⚠</span><small>Ошибки</small></button><button onclick='nav("infra")'><span class='ico'>◉</span><small>GitHub</small></button><button onclick='nav("infra")'><span class='ico'>☁</span><small>Render</small></button></div>"}
function home(){let t=data?.target||{},run=status?.status==="running",pct=status?.progress||0;el.innerHTML=run?process():`<div class="screen"><div class="hero"><div class="logo">⌕</div><h1>PMSignalPro Tester</h1><div class="subtitle">Полная read-only проверка проекта</div><span class="readonly">READ-ONLY</span><div class="info">◉ Только проверка · Ничего не изменяет</div><div class="target"><div class="mut">Тестируемый бот</div><b>${esc(t.name||"PMSignalPro")}</b><span>${esc(t.username||"@PMSignalPro_bot")}</span><button class="edit">✎</button></div><button class="test" onclick="start()">⌕<br>ТЕСТИРОВАТЬ<br><small>Полная проверка · 41 категория</small></button>${quick()}<div class="grid"><div class="card"><h3>Категории</h3><div class="num">41</div><div class="mut">полная проверка</div></div><div class="card"><h3>Режим</h3><div class="num">READ</div><div class="mut">без изменений</div></div></div></div></div>`}
function process(){let total=status?.total||41,n=status?.current||Math.round(total*(status?.progress||0)/100),pct=status?.progress||0;return `<div class="screen"><div class="card"><div class="process">Идёт полная проверка...</div><div class="process-sub">Проверяем все 41 категорию проекта.</div><div class="ring" style="--p:${pct}%"><b>${n}/${total}</b></div><div class="section-sub">${pct}%</div><div class="card"><div class="row"><span>Текущая категория</span><b>${esc(status?.current_name||"Подготовка...")}</b></div><div class="mut">Тестировщик проверяет файлы и структуру проекта в режиме READ-ONLY.</div></div></div></div>`}
async function start(){let r=await fetch("/api/test/start?session="+encodeURIComponent(session),{method:"POST"});if(!r.ok)return;clearInterval(timer);timer=setInterval(refresh,700);refresh()}
async function refresh(){status=await get("/api/test/status?session="+encodeURIComponent(session));home();if(status.status==="completed"||status.status==="failed"){clearInterval(timer);let r=await get("/api/test/report?session="+encodeURIComponent(session));if(r.ok)data={...data,report:r.report};nav("results")}}
function results(){let r=data?.report;if(!r){el.innerHTML="<div class='screen'><div class='card'>Нажмите «ТЕСТИРОВАТЬ».</div></div>";return}let c={PASS:0,WARNING:0,FAIL:0,"NOT TESTED":0};(r.categories||[]).forEach(x=>c[x.status]++);el.innerHTML=`<div class="screen"><div class="section-title">Проверка завершена!</div><div class="section-sub">Все 41 категория проверены</div><div class="summary"><div class="card"><span class="sum ok">✓</span><div><b>${c.PASS}</b><div class="mut">PASS</div></div></div><div class="card"><span class="sum warn">!</span><div><b>${c.WARNING}</b><div class="mut">WARNING</div></div></div><div class="card"><span class="sum fail">×</span><div><b>${c.FAIL}</b><div class="mut">FAIL</div></div></div><div class="card"><span class="sum not">○</span><div><b>${c["NOT TESTED"]}</b><div class="mut">NOT TESTED</div></div></div></div><div class="card" style="margin-top:9px"><div class="row"><span>Всего категорий</span><b>41</b></div><div class="row"><span>GitHub</span><b class="ok">Проверен</b></div><div class="row"><span>Render</span><b class="ok">Проверен</b></div><div class="row"><span>Режим</span><b>READ-ONLY</b></div></div><button class="btn" onclick="nav('resultsList')">▤ Открыть полный отчёт</button><button class="btn" onclick="nav('errors')">⚠ Список ошибок (${c.FAIL})</button></div>`}
function resultsList(){let r=data?.report;if(!r){nav("results");return}el.innerHTML="<div class='screen'><div class='section-title'>Полный отчёт (41 категория)</div><div class='section-sub'>Все результаты проверки</div><div class='list'>"+(r.categories||[]).map(x=>"<div class='card cat' onclick='detail("+Number(x.category)+")'><div class='row'><span>"+esc(x.category)+". "+esc(x.name)+"</span>"+badge(x.status)+"</div><div class='mut'>"+esc(x.detail||"")+"</div></div>").join("")+"</div></div>"}
function detail(n){let x=(data?.report?.categories||[]).find(v=>Number(v.category)===n);if(!x)return;el.innerHTML="<div class='screen'><div class='section-title'>Категория "+esc(x.category)+": "+esc(x.name)+"</div><div class='card'><div class='row'><b>Статус</b>"+badge(x.status)+"</div><p>"+esc(x.detail||"")+"</p><div class='mut'>Что проверено:</div>"+(x.evidence||[]).map(v=>"<div class='row'><span>"+esc(v.path||"Источник")+"</span><span class='ok'>✓</span></div>").join("")+"</div><button class='btn' onclick='resultsList()'>← Полный отчёт</button></div>"}
function errors(){let r=data?.report;if(!r){el.innerHTML="<div class='screen'><div class='section-title'>Список ошибок</div><div class='card'>Проверка ещё не выполнена.</div></div>";return}let e=(r.categories||[]).filter(x=>x.status==="FAIL"||x.status==="WARNING");el.innerHTML="<div class='screen'><div class='section-title'>Список ошибок</div><div class='section-sub'>Найдено ошибок: "+e.length+"</div>"+(e.length?e.map((x,i)=>"<div class='card error'><div class='row'><b>"+(i+1)+". "+esc(x.name)+"</b>"+badge(x.status)+"</div><p>"+esc(x.detail||"")+"</p></div>").join(""):"<div class='card'><b class='ok'>Ошибок не обнаружено.</b></div>")+"</div>"}
function infra(){let r=data?.report;if(!r){el.innerHTML="<div class='screen'><div class='section-title'>GitHub и Render</div><div class='card'>Данные появятся после проверки.</div></div>";return}let d=r.render?.last_deploy||{};el.innerHTML="<div class='screen'><div class='section-title'>GitHub и Render</div><div class='card'><h3>GitHub</h3><div class='row'><span>Статус</span>"+badge(r.repository?.status||"NOT TESTED")+"</div><div class='mut'>"+esc(r.target_repo||"")+"</div></div><div class='card'><h3>Render</h3><div class='row'><span>Статус</span>"+badge(r.render?.status||"NOT TESTED")+"</div><div class='mut'>"+esc(r.render?.detail||"")+"</div><div class='row'><span>Последний deploy</span><b>"+esc(d.status||"NOT TESTED")+"</b></div></div></div>"}
async function history(){let r=await get("/api/test/history");el.innerHTML="<div class='screen'><div class='section-title'>История проверок</div>"+((r.history||[]).length?(r.history||[]).map(h=>"<div class='card'><div class='row'><b>"+esc(h.target?.name||"Тест")+"</b><span class='ok'>✓</span></div><div class='mut'>PASS: "+h.summary.PASS+" · WARN: "+h.summary.WARNING+" · FAIL: "+h.summary.FAIL+"</div></div>").join(""):"<div class='card'>История пока пустая.</div>")+"</div>"}
function menu(){el.innerHTML="<div class='screen'><div class='section-title'>Меню разделов</div><div class='section-sub'>Выберите раздел для просмотра</div><div class='menu'><button onclick='results()'><span class='ico'>▥</span><b>Результаты</b><small>Полный отчёт по 41 категории</small></button><button onclick='errors()'><span class='ico'>⚠</span><b>Ошибки</b><small>Список проблем</small></button><button onclick='resultsList()'><span class='ico'>▣</span><b>Файлы</b><small>Проверка файлов</small></button><button onclick='infra()'><span class='ico'>◉</span><b>GitHub</b><small>Статус репозитория</small></button><button onclick='infra()'><span class='ico'>☁</span><b>Render</b><small>Статус сервиса</small></button><button onclick='history()'><span class='ico'>◷</span><b>История</b><small>Все проверки</small></button><button><span class='ico'>⚙</span><b>Настройки</b><small>Параметры отображения</small></button><button><span class='ico'>?</span><b>Помощь</b><small>Инструкция</small></button></div></div>"}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>nav(b.dataset.screen));

sessionLoad().then(()=>home());
