const qs=new URLSearchParams(location.search),session=qs.get("session"),tg=window.Telegram?.WebApp;
if(tg){tg.ready();tg.expand()}
const screen=document.getElementById("screen"),conn=document.getElementById("conn");
let data=null,status=null,poll=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
async function get(path){const r=await fetch(path);return r.json()}
async function loadSession(){if(!session){conn.textContent="Нет сессии";return}const r=await get("/api/session?session="+encodeURIComponent(session));if(r.ok){conn.textContent="Сессия готова";data=r}else conn.textContent="Сессия недоступна"}
async function start(){const r=await fetch("/api/test/start?session="+encodeURIComponent(session),{method:"POST"});if(!r.ok)return;clearInterval(poll);poll=setInterval(refresh,700);refresh()}
async function refresh(){status=await get("/api/test/status?session="+encodeURIComponent(session));render("home");if(status.status==="completed"||status.status==="failed"){clearInterval(poll);if(status.status==="completed"){const r=await get("/api/test/report?session="+encodeURIComponent(session));data={...data,report:r.report}}}}
function badge(s){return "<span class='badge "+(s==="PASS"?"pass":s==="WARNING"?"warning":s==="FAIL"?"failure":"not")+"'>"+esc(s)+"</span>"}
function render(name){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===name));({home,results,errors,infra,historyScreen}[name]||home)()}
function home(){const t=data?.target||{},running=status?.status==="running",p=status?.progress||0;screen.innerHTML="<div class='screen'><div class='hero'><div class='logo'>⌕</div><h1>PMSignalPro Tester</h1><div class='center muted'>Полная read-only проверка проекта</div><div class='target'><div class='mini'>Тестируемый бот</div><strong>"+esc(t.name||"—")+"</strong><span>"+esc(t.username||"—")+"</span></div>"+(running?"<div class='ring' style='--p:"+p+"%'><b>"+p+"%</b></div><div class='center'><b>Идёт полная проверка</b><p class='mini'>"+esc(status.current_name||"Подготовка...")+"</p></div><div class='progress'><i style='width:"+p+"%'></i></div>":"<button class='test-btn' onclick='start()'>⌕<br>ТЕСТИРОВАТЬ</button><div class='grid'><div class='card'><h3>Категории</h3><div class='stat'>41</div><div class='mini'>полная проверка</div></div><div class='card'><h3>Режим</h3><div class='stat'>READ</div><div class='mini'>без изменений</div></div></div>")+"</div></div>"}
function results(){const r=data?.report;if(!r){screen.innerHTML="<div class='screen'><div class='section-title'>Результаты</div><div class='card'>Сначала нажмите «ТЕСТИРОВАТЬ».</div></div>";return}const c={PASS:0,WARNING:0,FAIL:0,"NOT TESTED":0};r.categories.forEach(x=>c[x.status]++);screen.innerHTML="<div class='screen'><div class='section-title'>Полный отчёт · 41 категория</div><div class='grid'><div class='card'><h3>PASS</h3><div class='stat ok'>"+c.PASS+"</div></div><div class='card'><h3>WARNING</h3><div class='stat warn'>"+c.WARNING+"</div></div><div class='card'><h3>FAIL</h3><div class='stat fail'>"+c.FAIL+"</div></div><div class='card'><h3>NOT TESTED</h3><div class='stat neutral'>"+c["NOT TESTED"]+"</div></div></div><div class='list'>"+r.categories.map(x=>"<div class='card'><div class='row'><span>"+x.category+". "+esc(x.name)+"</span>"+badge(x.status)+"</div><div class='mini'>"+esc(x.detail)+"</div></div>").join("")+"</div></div>"}
function errors(){const r=data?.report;if(!r){screen.innerHTML="<div class='screen'><div class='section-title'>Ошибки</div><div class='card'>Ошибки появятся после проверки.</div></div>";return}const e=r.categories.filter(x=>x.status==="FAIL"||x.status==="WARNING");screen.innerHTML="<div class='screen'><div class='section-title'>Ошибки и предупреждения</div>"+(e.length?e.map(x=>"<div class='card error'><div class='row'><b>"+x.category+". "+esc(x.name)+"</b>"+badge(x.status)+"</div><p>"+esc(x.detail)+"</p>"+(x.evidence||[]).map(v=>"<div class='mini'>"+esc(v.path)+" · "+esc(v.syntax||"")+"</div>").join("")+"</div>").join(""):"<div class='card'><span class='ok'>Ошибок не обнаружено.</span></div>")+"</div>"}
function infra(){const r=data?.report;if(!r){screen.innerHTML="<div class='screen'><div class='section-title'>GitHub и Render</div><div class='card'>Данные появятся после проверки.</div></div>";return}const rd=r.render||{},d=rd.last_deploy||{};screen.innerHTML="<div class='screen'><div class='section-title'>GitHub и Render</div><div class='card'><h3>GitHub</h3><div class='row'><span>Репозиторий</span>"+badge(r.repository.status)+"</div><div class='mini'>"+esc(r.target_repo)+"</div><div class='mini'>Файлов: "+r.repository.file_count+"</div></div><div class='card'><h3>Render</h3><div class='row'><span>Сервис</span>"+badge(rd.status)+"</div><div class='mini'>"+esc(rd.detail||"—")+"</div><div class='row'><span>Последний запуск</span><b>"+esc(d.status||"NOT TESTED")+"</b></div><div class='mini'>"+esc(d.finishedAt||d.createdAt||"—")+"</div></div><div class='card'><h3>HTTP</h3><div class='row'><span>/health</span>"+badge(r.http.status)+"</div><div class='mini'>"+esc(r.http.detail)+"</div></div></div>"}
async function historyScreen(){const r=await get("/api/test/history");screen.innerHTML="<div class='screen'><div class='section-title'>История проверок</div>"+((r.history||[]).length?(r.history||[]).map(h=>"<div class='card'><b>"+esc(h.target?.name||"Тест")+"</b><div class='mini'>PASS "+h.summary.PASS+" · WARN "+h.summary.WARNING+" · FAIL "+h.summary.FAIL+"</div></div>").join(""):"<div class='card'>История пока пустая.</div>")+"</div>"}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>render(b.dataset.screen));
loadSession().then(()=>render("home"));
